repos:
- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black", "--filter-files"]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: requirements-txt-fixer
    - id: name-tests-test
    - id: check-added-large-files