[pytest]
pythonpath=src
testpaths=src
markers=
    schema: test about YAML config file schema
    dsl: test about config DSL
    config: test about config workflow
    templating: test about expression templating